import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Luis Castrillo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="icon"
          href="/images/logo.png"
          type="image/png"
          sizes="512x509"
        />
      </head>
      <body
        id="layout-body"
        className={`${inter.className} bg-primary min-h-screen min-w-screen text-primary overflow-x-hidden dark:bg-dark-primary dark:text-dark-primary transition-color ease-[cubic-bezier(0.645,0.045,0.355,1)] duration-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
